### ISSUE TITLE
failed to invoke `swc-plugin-jsx-control-statements` as js transform plugin at node_modules

### ISSUE THREAD

**Issue by mengyjd** [intpp/swc-plugin-jsx-control-statements#2]
I encountered an error when using optional chain syntax.
example code:
```
if (!selectRow?.pk_accasoa) {
   return;
}
```

errors:

```
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("D:\\yonyou\\project\\tdcwgk_front\\src\\gl\\gl_voucher\\container\\Welcome\\utils\\linkAssistDetail.js")'

Caused by:
    0: failed to invoke `swc-plugin-jsx-control-statements` as js transform plugin at node_modules\swc-plugin-jsx-control-statements\swc_plugin_jsx_control_statements.wasm
    1: RuntimeError: out of bounds memory access
           at <unnamed> (<module>[86]:0x1bdb0)
           at <unnamed> (<module>[86]:0x199d6)
           at <unnamed> (<module>[86]:0x19c26)
           at <unnamed> (<module>[86]:0x19c26)
           at <unnamed> (<module>[159]:0x38318)
           at <unnamed> (<module>[152]:0x35896)
           at <unnamed> (<module>[117]:0x2bc74)
           at <unnamed> (<module>[115]:0x27fae)

× React-typescript-boilerplate
  Compiled with some errors in 309.49ms

ERROR in ./src/gl/gl_voucher/container/Welcome/utils/linkAssistDetail.js
Module build failed (from ./node_modules/swc-loader/src/index.js):
Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("D:\\yonyou\\project\\tdcwgk_front\\src\\gl\\gl_voucher\\container\\Welcome\\utils\\linkAssistDetail.js")'

Caused by:
    0: failed to invoke `swc-plugin-jsx-control-statements` as js transform plugin at node_modules\swc-plugin-jsx-control-statements\swc_plugin_jsx_control_statements.wasm
    1: RuntimeError: out of bounds memory access
           at <unnamed> (<module>[86]:0x1bdb0)
           at <unnamed> (<module>[86]:0x199d6)
```

**Comment by intpp** [comment]
Hi. Could you provide the whole component's code or an example of a component's code that is causing the error?

**Comment by jeron-diovis** [comment]
Got similar error with this plugin.
Full trace:
```
10% building 0/2 entries 4/6 dependencies 0/3 modulesthread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.42/src/impls/core/mod.rs:266:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
60% building 1/2 entries 18/18 dependencies 10/11 modulesthread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.273.5/src/plugin.rs:162:14:
failed to invoke plugin: failed to invoke plugin on 'Some("/Users/jeron_diovis/dev/projects/Quantum/QuantumSite/frontend/storybook-config-entry.js")'

Caused by:
    0: failed to invoke `swc-plugin-jsx-control-statements` as js transform plugin at swc-plugin-jsx-control-statements
    1: RuntimeError: unreachable
           at <unnamed> (<module>[650]:0xb0ed7)
           at <unnamed> (<module>[505]:0x92233)
           at <unnamed> (<module>[657]:0xb14c2)
           at <unnamed> (<module>[656]:0xb13fb)
           at <unnamed> (<module>[373]:0x717a6)
           at <unnamed> (<module>[17]:0x1a1f)
           at <unnamed> (<module>[13]:0x11a3)
           at <unnamed> (<module>[134]:0x335ad)
           at <unnamed> (<module>[86]:0x1a7e9)
           at <unnamed> (<module>[142]:0x33c65)
           at <unnamed> (<module>[86]:0x1ae5c)
           at <unnamed> (<module>[118]:0x2c1fc)
           at <unnamed> (<module>[115]:0x28099)
           at <unnamed> (<module>[159]:0x39ef2)
           at <unnamed> (<module>[60]:0xd610)
           at <unnamed> (<module>[329]:0x6b804)
           at <unnamed> (<module>[772]:0xc89c5)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR in ./storybook-config-entry.js
Module build failed (from ./node_modules/@storybook/builder-webpack5/node_modules/swc-loader/src/index.js):
Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("/Users/jeron_diovis/dev/projects/Quantum/QuantumSite/frontend/storybook-config-entry.js")'

Caused by:
    0: failed to invoke `swc-plugin-jsx-control-statements` as js transform plugin at swc-plugin-jsx-control-statements
    1: RuntimeError: unreachable
           at <unnamed> (<module>[650]:0xb0ed7)
           at <unnamed> (<module>[505]:0x92233)
           at <unnamed> (<module>[657]:0xb14c2)
           at <unnamed> (<module>[656]:0xb13fb)
           at <unnamed> (<module>[373]:0x717a6)
           at <unnamed> (<module>[17]:0x1a1f)
           at <unnamed> (<module>[13]:0x11a3)
           at <unnamed> (<module>[134]:0x335ad)
           at <unnamed> (<module>[86]:0x1a7e9)
           at <unnamed> (<module>[142]:0x33c65)
           at <unnamed> (<module>[86]:0x1ae5c)
           at <unnamed> (<module>[118]:0x2c1fc)
           at <unnamed> (<module>[115]:0x28099)
           at <unnamed> (<module>[159]:0x39ef2)
           at <unnamed> (<module>[60]:0xd610)
           at <unnamed> (<module>[329]:0x6b804)
           at <unnamed> (<module>[772]:0xc89c5)

preview compiled with 1 error
=> Failed to build the preview
99% end closing watch compilationWARN Force closed preview build
SB_BUILDER-WEBPACK5_0003 (WebpackCompilationError): There were problems when compiling your code with Webpack.
Run Storybook with --debug-webpack for more information.
    at starter (./node_modules/@storybook/builder-webpack5/dist/index.js:1:9660)
    at starter.next (<anonymous>)
    at Module.start (./node_modules/@storybook/builder-webpack5/dist/index.js:1:11692)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.


Process finished with exit code 1
```

My component contains nothing but `<div><If>...</If></div>`.

Storybook v7.6.16 with react-webpack5  framework.
